# Generated by Django 4.2.5 on 2023-09-18 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('vehicles_processed', models.IntegerField(default=0)),
                ('charges_collected', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_num', models.CharField(max_length=10)),
                ('pid', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('0', 'TWO_WHEELER'), ('1', 'FOUR_WHEELER')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleProcessed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toll_pid', models.UUIDField()),
                ('vehicle_pid', models.UUIDField()),
                ('charge', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toll_pid', models.UUIDField()),
                ('pass_type', models.CharField(choices=[('0', 'single'), ('1', 'return'), ('2', 'seven days')], max_length=20)),
                ('is_valid', models.BooleanField(default=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_passes', to='toll_ms.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='TollPriceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('0', 'TWO_WHEELER'), ('1', 'FOUR_WHEELER')], max_length=20)),
                ('single_pass', models.FloatField()),
                ('return_pass', models.FloatField()),
                ('seven_day_pass', models.FloatField()),
                ('toll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toll_ms.toll')),
            ],
        ),
    ]
